#!/usr/bin/env python3
"""Cut the offline suite's fixtures out of real captures, and PROVE they parse
the same.

Its output is `fixtures_generated.json`, which `smoke_test.py` loads.

WHY A GENERATED FILE RATHER THAN INLINE LITERALS
------------------------------------------------
The family's rule is fixtures inline in `smoke_test.py`. Here a fixture is an
API response: one search record is ~3 KB of JSON with nine photo paths.
Pasting those into a Python source file as string literals would make the
suite unreadable. The generated JSON sits beside it, is regenerated by this
script, and is checked by the suite for the same properties inline fixtures
would be. Sibling repos (rakuten, binance) do the same for the same reason.

WHAT YOU NEED TO RUN IT
-----------------------
Your own captures, in `captures/` (ignored by git), taken with
`tools/capture.py`, which names them as SOURCES below expects.

WHAT IT ENFORCES
----------------
  * every fixture is CUT from a real capture, never hand-written;
  * each one parses IDENTICALLY to the untrimmed original for the records
    it keeps, every column, apart from the columns the scrub replaced;
  * the scrub runs BEFORE anything is embedded:
      - a PRIVATE seller (`SellerType: PF`) is a person. Their seller id,
        first name, phone, postal code and their own description of their
        car are replaced with placeholders. The parser never writes the
        name, phone, postal code or description anyway (product_parser), and
        the checks need the STRUCTURE of the record, not the person;
      - the exit's IP address, coordinates and postal code in the
        /api/location landing, and any IP in a page, become documentation
        addresses (192.0.2.0/24);
      - PerimeterX's per-visit UUID and CloudFront's Request ID, which
        identify the session that fetched them;
      - the search response's `Filters` list (the site's facet menu, 27
        entries and most of every page's bytes), which nothing reads;
  * a fixture that still holds a 32-hex string after the scrub is refused.

    python3 make_fixtures.py [captures_dir]
"""
import copy
import json
import pathlib
import re
import sys
from dataclasses import asdict

REPO = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(REPO))

from product_parser import Query, currency_from_html, parse_page  # noqa: E402

HEX32 = re.compile(r"\b[0-9a-f]{32}\b")
IPV4 = re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")

GOL = "https://www.webmotors.com.br/carros/estoque/volkswagen/gol"
Q_GOL = Query("search", listing_url=GOL, make="volkswagen", model="gol")
Q_GOL_ASC = Query("search", listing_url=GOL, sort="price-asc",
                  make="volkswagen", model="gol")
Q_HONDA = Query("search", listing_url="https://www.webmotors.com.br/motos/estoque/honda",
                vehicle="motos", make="honda")
Q_SP = Query("search", listing_url="https://www.webmotors.com.br/carros/sp/toyota",
             make="toyota", state="SP")
Q_ALL = Query("search", listing_url="https://www.webmotors.com.br/carros/estoque")

# name -> (capture file, query, records kept, kind)
SOURCES = {
    "search_gol_p1": ("search_gol_p1.json", Q_GOL, 5, "search"),
    "search_gol_p2": ("search_gol_p2.json", Q_GOL, 5, "search"),
    "search_gol_price_asc_p1": ("search_gol_price_asc_p1.json", Q_GOL_ASC, 6, "search"),
    "search_motos_honda_p1": ("search_motos_honda_p1.json", Q_HONDA, 4, "search"),
    "search_sp_toyota_p1": ("search_sp_toyota_p1.json", Q_SP, 3, "search"),
    "search_typo_model": ("search_typo_model.json", None, 1, "search"),
    "search_bogus_make": ("search_bogus_make.json", None, 1, "search"),
    # Kept whole up to the last sponsored tile, so the fixture holds the
    # tiles AND the listings around them in the order the site sent them.
    "search_estoque_sponsored": ("search_estoque_sponsored.json", Q_ALL, "sponsored", "search"),
    "search_gol_past_end": ("search_gol_past_end.json", Q_GOL, 0, "search"),
    # Page 500 of a 40-page search. Kept: the records that are ALSO on the
    # kept part of page 1, which is the point of the fixture.
    "search_gol_far_past_end": ("search_gol_far_past_end.json", Q_GOL, "page1", "search"),
    "detail_car_dealer": ("detail_car_dealer.json", "ad", None, "detail"),
    "detail_car_private": ("detail_car_private.json", "ad", None, "detail"),
    "detail_bike": ("detail_bike.json", "ad", None, "detail"),
    "avg_car_dealer": ("avg_car_dealer.json", None, None, "json"),
    "avg_bike": ("avg_bike.json", None, None, "json"),
    "location": ("location.json", None, None, "location"),
    "detail_gone": ("detail_gone.txt", None, None, "status-text"),
    "gateway_403": ("gateway_403.txt", None, None, "status-text"),
    "listing_gol_jsonld": ("listing_gol.html", None, None, "jsonld"),
    "advert_shell_jsonld": ("advert_shell.html", None, None, "jsonld"),
    "px_refusal": ("px_refusal.html", None, None, "text"),
    "cloudfront_403": ("cloudfront_403.html", None, None, "text"),
    # A page fetched over --cdp-endpoint: the Scraping Browser's auto-solve
    # extension injects its hunter scripts into every page it loads, and the
    # marker set must score zero against them (CLAUDE.md §24).
    "cdp_landing": ("cdp_landing.html", None, None, "text"),
}

# Columns the scrub replaces. Everything else must survive unchanged.
SCRUBBED_COLUMNS = {"seller_id"}

PRIVATE_TEXT = "fixture: a private seller's own description, removed"


def _scrub_seller(rec: dict, i: int) -> None:
    seller = rec.get("Seller")
    if not isinstance(seller, dict) or seller.get("SellerType") != "PF":
        return
    seller["Id"] = 900000 + i
    if "FirstName" in seller:
        seller["FirstName"] = "Fixture"
    for ph in seller.get("Phones") or []:
        if isinstance(ph, dict):
            ph["Value"] = "(00) 0000"
    for loc in seller.get("Localization") or []:
        if isinstance(loc, dict) and loc.get("ZipCode"):
            loc["ZipCode"] = "00000000"
    if rec.get("LongComment"):
        rec["LongComment"] = PRIVATE_TEXT


def _trim_search(payload: dict, keep, name: str, page1: dict) -> dict:
    p = copy.deepcopy(payload)
    p.pop("Filters", None)
    rows = p.get("SearchResults") or []
    if keep == "sponsored":
        last = max(i for i, r in enumerate(rows) if not r.get("UniqueId"))
        rows = rows[:last + 2]
    elif keep == "page1":
        kept_p1 = {r.get("UniqueId") for r in page1["SearchResults"]}
        rows = [r for r in rows if r.get("UniqueId") in kept_p1]
    else:
        rows = rows[:keep]
    for r in rows:
        media = r.get("Media")
        if isinstance(media, dict) and isinstance(media.get("Photos"), list):
            media["Photos"] = media["Photos"][:2]
    p["SearchResults"] = rows
    return p


def _rows(payload, query):
    return [asdict(r) for r in parse_page(json.dumps(payload), query)]


def _same(orig_rows, new_rows) -> list:
    skip = SCRUBBED_COLUMNS | {"scraped_at", "photo_count"}
    problems = []
    for i, (a, b) in enumerate(zip(orig_rows, new_rows)):
        for k in a:
            if k not in skip and a[k] != b[k]:
                problems.append("row %d column %s: %r -> %r" % (i, k, a[k], b[k]))
    return problems


def _scrub_text(text: str) -> str:
    text = IPV4.sub(lambda m: "127.0.0.1" if m.group(0) == "127.0.0.1"
                    else "192.0.2.1", text)
    text = re.sub(r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
                  "00000000-0000-0000-0000-000000000000", text)
    text = re.sub(r"(Request ID: )[^<\s]+", r"\1FIXTURE-REQUEST-ID", text)
    return text


def main(argv) -> int:
    captures = pathlib.Path(argv[1]) if len(argv) > 1 else REPO / "captures"
    out, problems = {}, []
    page1 = None
    for name, (fname, query, keep, kind) in SOURCES.items():
        raw = (captures / fname).read_text(encoding="utf-8")
        if kind == "text":
            out[name] = _scrub_text(raw)
            continue
        if kind == "status-text":
            status, _, body = raw.partition("\n")
            out[name] = {"status": int(status), "body": body}
            continue
        if kind == "jsonld":
            blocks = re.findall(r'<script[^>]*application/ld\+json[^>]*>.*?</script>',
                                raw, re.S)
            fixture = "<html><head>%s</head><body></body></html>" % "".join(blocks)
            if currency_from_html(fixture) != currency_from_html(raw):
                problems.append("%s: the cut reads a different currency" % name)
            out[name] = fixture
            continue
        payload = json.loads(raw)
        if kind == "location":
            r = payload.get("response", {})
            out[name] = {"response": {"edge-country": r.get("edge-country"),
                                      "edge-two-letter-country": r.get("edge-two-letter-country"),
                                      "ip": "192.0.2.1"}}
            continue
        if kind == "search":
            fixture = _trim_search(payload, keep, name, page1 or payload)
            for i, rec in enumerate(fixture["SearchResults"], 1):
                _scrub_seller(rec, i)
            if name == "search_gol_p1":
                page1 = fixture
            if query is not None:
                orig = {r["sku"]: r for r in _rows(payload, query)}
                new = _rows(fixture, query)
                expected = [str(r["UniqueId"]) for r in fixture["SearchResults"]
                            if r.get("UniqueId") and not r.get("MediaZeroKm")]
                if [r["sku"] for r in new] != expected:
                    problems.append("%s: parsed %s, kept %s" % (name, [r["sku"] for r in new], expected))
                # Positions shift when a trim drops records ABOVE a kept one;
                # compare everything else row by row.
                problems += ["%s: %s" % (name, p) for p in _same(
                    [dict(orig[r["sku"]], position=r["position"]) for r in new], new)]
        elif kind == "detail":
            fixture = copy.deepcopy(payload)
            media = fixture.get("Media")
            if isinstance(media, dict) and isinstance(media.get("Photos"), list):
                media["Photos"] = media["Photos"][:2]
            _scrub_seller(fixture, 1)
        else:
            fixture = payload
        blob = json.dumps(fixture)
        if HEX32.search(blob):
            problems.append("%s: a 32-hex string survived the scrub" % name)
        if IPV4.search(blob) and name != "location":
            problems.append("%s: an IPv4 address survived the scrub" % name)
        out[name] = fixture
    if problems:
        print("[!] NOT writing fixtures_generated.json:")
        for p in problems:
            print("    " + p)
        return 1
    target = REPO / "fixtures_generated.json"
    target.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n",
                      encoding="utf-8")
    print("[+] wrote %s: %d fixtures, %d bytes"
          % (target.name, len(out), target.stat().st_size))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
