#!/usr/bin/env python3
"""Cut the offline suite's fixtures out of real captures, and PROVE they parse
the same.

Its output is `fixtures_generated.json`, which `smoke_test.py` loads.

WHY A GENERATED FILE RATHER THAN INLINE LITERALS
------------------------------------------------
The family's rule is fixtures inline in `smoke_test.py`. Here a fixture is an
API response: one P2P advert is ~3 KB of JSON and one copy-trading record
carries a 30-point chart. Pasting those into a Python source file as string
literals would make the suite unreadable. The generated JSON sits beside it,
is regenerated by this script, and is checked by the suite for the same
properties inline fixtures would be. Two sibling repos (rakuten, polymarket)
do the same for the same reason.

WHAT YOU NEED TO RUN IT
-----------------------
Your own captures, in `captures/` (ignored by git), named as the SOURCES
table below expects. Take them with `--dump-html`, which writes exactly the
JSON the parser was given, or with curl against the endpoints
product_parser.py names.

WHAT IT ENFORCES
----------------
  * every fixture is CUT from a real capture, never hand-written;
  * each one parses IDENTICALLY to the untrimmed original for the records
    it keeps, every column, apart from the columns the scrub replaced;
  * the scrub runs BEFORE anything is embedded:
      - P2P advertiser nicknames and ids, and copy-trading nicknames and
        avatar URLs. They are public pseudonymous handles the site shows
        every visitor, and the checks need the structure rather than a
        person's handle;
      - announcement `code`s, which are 32 hex characters, the exact shape of
        an API key. The parser only needs a code to exist;
  * a fixture that still holds a 32-hex string after the scrub is refused.

    python3 make_fixtures.py [captures_dir]
"""
import copy
import json
import os
import pathlib
import re
import sys
from dataclasses import asdict

REPO = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(REPO))

from product_parser import Query, parse_page  # noqa: E402

HEX32 = re.compile(r"\b[0-9a-f]{32}\b")

# name -> (capture file, query, records kept, kind)
SOURCES = {
    "p2p_usdt_eur_buy": ("p2p_usdt_eur_buy_p1.json",
                         Query("p2p", asset="USDT", fiat="EUR", side="buy"), 4, "json"),
    "p2p_btc_try_sell": ("p2p_btc_try_sell_p1.json",
                         Query("p2p", asset="BTC", fiat="TRY", side="sell"), 3, "json"),
    "p2p_past_the_end": ("p2p_usdt_eur_buy_p99.json",
                         Query("p2p", asset="USDT", fiat="EUR"), None, "json"),
    "p2p_illegal_rows": ("p2p_rows50.json", Query("p2p"), None, "json"),
    "p2p_pay_types_eur": ("p2p_filter_eur.json", None, None, "json"),
    "copy_30d_roi": ("copy_30d_roi_p1.json", Query("copytrading"), 3, "json"),
    "copy_7d_pnl": ("copy_7d_pnl_p1.json",
                    Query("copytrading", time_range="7D", sort_by="pnl"), 3, "json"),
    "copy_past_the_end": ("copy_30d_roi_p999.json", Query("copytrading"), None, "json"),
    "ann_new_listings": ("ann_48_p1.json", Query("announcements"), 3, "json"),
    "ann_delisting": ("ann_161_p1.json",
                      Query("announcements", catalog="delisting"), 3, "json"),
    "ann_past_the_end": ("ann_48_p999.json", Query("announcements"), None, "json"),
    "waf_captcha_chromium": ("waf_captcha_chromium.html", None, None, "text"),
    # The Scraping Browser extension's injected tags, cut from a sibling
    # repo's --cdp-endpoint capture: the injection is the extension's own and
    # identical on every site (see the comment at the top of the file).
    "cdp_extension_injection": ("cdp_extension_tags.html", None, None, "text"),
}

# Columns the scrub replaces, per mode. Everything else must survive the
# trim unchanged.
SCRUBBED_COLUMNS = {
    "p2p": {"title", "advertiser_id", "url"},
    "copytrading": {"title"},
    "announcements": {"url"},
}


def _trim(payload: dict, keep: int) -> dict:
    p = copy.deepcopy(payload)
    data = p.get("data")
    if isinstance(data, list):
        p["data"] = data[:keep]
    elif isinstance(data, dict) and isinstance(data.get("list"), list):
        data["list"] = data["list"][:keep]
        for rec in data["list"]:
            if isinstance(rec.get("chartItems"), list):
                rec["chartItems"] = rec["chartItems"][:2]
    elif isinstance(data, dict) and isinstance(data.get("catalogs"), list):
        for cat in data["catalogs"]:
            cat["articles"] = cat["articles"][:keep]
    return p


def _scrub(payload: dict) -> dict:
    p = copy.deepcopy(payload)
    data = p.get("data")
    if isinstance(data, list):
        for i, rec in enumerate(data, 1):
            who = rec.get("advertiser") or {}
            if who.get("nickName") is not None:
                who["nickName"] = "fixture-advertiser-%d" % i
            if who.get("userNo") is not None:
                who["userNo"] = "sFIXTURE-ADVERTISER-%d" % i
    elif isinstance(data, dict) and isinstance(data.get("list"), list):
        for i, rec in enumerate(data["list"], 1):
            rec["nickname"] = "fixture-lead-%d" % i
            if rec.get("avatarUrl"):
                rec["avatarUrl"] = "https://example.invalid/avatar-%d.png" % i
    elif isinstance(data, dict) and isinstance(data.get("catalogs"), list):
        n = 0
        for cat in data["catalogs"]:
            for art in cat.get("articles") or []:
                n += 1
                art["code"] = "fixture-code-%d" % n
            if cat.get("icon"):
                cat["icon"] = "https://example.invalid/catalog-icon.png"
    if isinstance(data, dict) and isinstance(data.get("tradeMethods"), list):
        # The filter-conditions list: keep the identifiers and names the
        # checks use, drop icon paths.
        for m in data["tradeMethods"]:
            m["iconUrlColor"] = None
    return p


def _rows(payload, query):
    return [asdict(r) for r in parse_page(json.dumps(payload), query)]


def _same(orig_rows, new_rows, mode) -> list:
    skip = SCRUBBED_COLUMNS.get(mode, set()) | {"scraped_at"}
    problems = []
    for i, (a, b) in enumerate(zip(orig_rows, new_rows)):
        for k in a:
            if k not in skip and a[k] != b[k]:
                problems.append("row %d column %s: %r -> %r" % (i, k, a[k], b[k]))
    return problems


def main(argv) -> int:
    captures = pathlib.Path(argv[1]) if len(argv) > 1 else REPO / "captures"
    out, problems = {}, []
    for name, (fname, query, keep, kind) in SOURCES.items():
        path = captures / fname
        raw = path.read_text(encoding="utf-8")
        if kind == "text":
            out[name] = raw
            continue
        payload = json.loads(raw)
        trimmed = _trim(payload, keep) if keep else copy.deepcopy(payload)
        if name == "p2p_pay_types_eur":
            methods = trimmed["data"]["tradeMethods"]
            trimmed["data"] = {"tradeMethods": methods[:12]}
        fixture = _scrub(trimmed)
        if query is not None and keep:
            orig = _rows(payload, query)[:keep]
            new = _rows(fixture, query)
            if len(new) != keep:
                problems.append("%s: kept %d records, parsed %d rows"
                                % (name, keep, len(new)))
            problems += ["%s: %s" % (name, p) for p in _same(orig, new, query.mode)]
        blob = json.dumps(fixture)
        if HEX32.search(blob):
            problems.append("%s: a 32-hex string survived the scrub" % name)
        out[name] = fixture
    if problems:
        print("[!] NOT writing fixtures_generated.json:")
        for p in problems:
            print("    " + p)
        return 1
    target = REPO / "fixtures_generated.json"
    target.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n",
                      encoding="utf-8")
    print("[+] wrote %s: %d fixtures, %d bytes"
          % (target.name, len(out), target.stat().st_size))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
